-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 20, 2025 at 01:34 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `budaya_dayak`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int(10) NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(10) NOT NULL,
  `level` enum('on','off') NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `foto` varchar(255) DEFAULT 'default.jpg'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `email`, `username`, `password`, `level`, `created_at`, `foto`) VALUES
(242433, 'clody@gmail.com', 'clowly', '2323', 'on', '2025-07-27 02:18:09', 'admin_1760941030.jpg'),
(242447, 'alfinnmaulana@gmail.com', 'alpin', '$2y$10$xDV', 'on', '2025-10-03 09:25:45', 'default.jpg'),
(242448, 'fahriiii@gmail.com', 'fardioz', '$2y$10$xDq', 'on', '2025-10-03 09:35:52', 'default.jpg'),
(242452, 'ikhsan99@gmail.com', 'ikhsan', '3737', 'on', '2025-10-04 23:20:50', '1759594850_spring cherry lemonade.jpg'),
(242453, 'alyamaharani@gmail.com', 'alya', '$2y$10$smz', 'off', '2025-10-11 22:03:08', '1760194988_strawberry cheese cake.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `isi_kategori`
--

CREATE TABLE `isi_kategori` (
  `id` int(10) NOT NULL,
  `kategori_id` int(10) NOT NULL,
  `nama_item` varchar(100) NOT NULL,
  `deskripsi` longtext DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `sumber_foto` varchar(255) DEFAULT NULL,
  `foto` varchar(255) DEFAULT 'default.jpg'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `isi_kategori`
--

INSERT INTO `isi_kategori` (`id`, `kategori_id`, `nama_item`, `deskripsi`, `link`, `sumber_foto`, `foto`) VALUES
(14, 22, 'Kohotong', 'Alat musik tradisional Kohotong berasal dari Kalimantan Barat dan termasuk jenis alat musik tiup. Cara memainkannya hampir sama dengan alat musik seruling dari Pulau Jawa, namun memiliki ciri khas tersendiri, yaitu bagian ujung Kohotong dibuat lebih besar daripada batangnya, menyerupai setengah bola.\r\n\r\nKohotong dibuat dari bahan kayu tertentu, yang pemilihannya tidak boleh sembarangan. Kayu yang digunakan tidak boleh berasal dari pohon liar atau dahan pohon enau, karena hal ini akan memengaruhi kualitas suara alat musik. Kohotong memiliki 7 lubang yang berfungsi sebagai pengatur bunyi atau nada yang dihasilkan, sehingga pemain dapat menciptakan melodi yang khas dan harmonis.\r\n\r\nDengan bunyi yang lembut dan karakteristik uniknya, Kohotong menjadi salah satu simbol kreativitas dan kearifan lokal masyarakat Kalimantan Barat yang terus dilestarikan sebagai bagian dari warisan budaya musik tradisional.', 'https:/www.youtube.com/embed/wFEFlBtnN0g', 'tambahpinter.com', 'item_14_1760888436.webp'),
(15, 22, 'Tuma', 'Alat musik tradisional Tuma berasal dari Kalimantan Barat dan termasuk jenis perkusi tradisional. Tuma biasanya digunakan oleh masyarakat Dayak sebagai pengiring tarian adat, upacara ritual, dan berbagai perayaan komunitas.\r\n\r\nAlat musik ini terbuat dari bahan kayu pilihan yang diproses sedemikian rupa agar menghasilkan bunyi khas ketika dipukul. Tuma dimainkan dengan ditabuh menggunakan telapak tangan atau alat pemukul sederhana, sehingga dapat menciptakan ritme yang stabil dan harmonis.\r\n\r\nTuma memiliki peran penting dalam kehidupan budaya masyarakat Dayak. Selain sebagai alat musik pengiring, Tuma juga dianggap sebagai simbol kebersamaan dan identitas budaya, yang menguatkan nilai-nilai tradisi dalam setiap pertunjukan seni atau upacara adat. Dengan keunikan suara dan fungsi sosialnya, Tuma tetap dijaga dan dilestarikan oleh masyarakat setempat hingga saat ini.', 'https://www.youtube.com/embed/K7axSvGRA1g', 'khatulistiwahits.com', 'item_15_1760888500.jpeg'),
(16, 22, 'Sape\'', 'Alat musik tradisional Sape merupakan salah satu kekayaan budaya khas Suku Dayak yang namanya berarti “memetik jari”. Penyebutan alat musik ini berbeda-beda di kalangan suku Dayak, misalnya Sampe’, Sempe, atau Kecapai, tergantung kelompok sukunya, sementara Suku Dayak Kenayan dan Kenyah menyebutnya “Sape”.\r\n\r\nSape berfungsi sebagai alat musik upacara sekaligus alat kesenian, biasanya dimainkan oleh seorang pria. Dalam kepercayaan masyarakat Dayak, perempuan tidak diperbolehkan memainkan Sape, karena dipercaya akan terkena kutukan dari dewa, misalnya mengalami perubahan fisik yang tidak wajar.\r\n\r\nPembuatan Sape menggunakan berbagai jenis kayu yang khas, seperti kayu Aro atau Adau (cephalomappa), kayu Marong, dan kayu Pelantan, yang banyak ditemukan di hutan Kalimantan. Saat ini, selain kayu tradisional tersebut, masyarakat juga menggunakan kayu lain seperti kayu nangka, Sana Keeling, Pule, dan sejenisnya untuk membuat Sape. Dengan bunyi yang merdu dan bentuk yang indah, Sape menjadi simbol kreativitas, identitas budaya, dan nilai spiritual masyarakat Dayak.', 'https://www.youtube.com/embed/Xb7qtkKqXjY', 'share.google', 'item_1759888960.jpeg'),
(18, 22, 'Agukng atau Gong', 'Alat musik tradisional Agukng berasal dari Kalimantan Barat dan dikenal sebagai salah satu alat musik yang sering dimainkan dan dianggap sakral. Instrumen ini hampir selalu ditemui di seluruh kelompok Dayak dan dipercaya diturunkan langsung oleh para dewa dari kayangan sebagai pengiring upacara adat.\r\n\r\nAgukng memiliki makna spiritual yang mendalam. Suara yang dihasilkan dipercaya mampu mengusir roh jahat sekaligus memanggil roh para leluhur atau makhluk gaib, sehingga alat musik ini menjadi bagian penting dalam berbagai ritual adat. Bunyi Agukng dianggap sebagai simbol keagungan, menandai kedatangan roh yang membantu pelaksanaan upacara.\r\n\r\nSelain perannya dalam ritual, Agukng juga memiliki nilai sosial dan simbolik. Alat musik ini dianggap sebagai lambang kebangsawanan dan kekayaan pemiliknya, karena dulunya dijadikan mas kawin dan hanya dimiliki oleh orang-orang tertentu. Dengan nilai spiritual, sosial, dan sejarahnya, Agukng menjadi salah satu simbol identitas budaya dan warisan sakral masyarakat Dayak di Kalimantan Barat yang sangat berharga.', 'https://www.youtube.com/embed/N0gmHcXuG2Y', 'wadaya.rey1024.com', '1759889311_Agukng atau Gong.webp'),
(19, 22, 'Balikan atau Kurating', 'Alat musik tradisional Balikan, yang juga dikenal sebagai Kurating, termasuk jenis alat musik petik dan masih satu keluarga dengan Sapek. Alat musik ini berasal dari Kapuas Hulu dan dibuat oleh masyarakat Dayak Ibanik dan Dayak Banuaka.\r\n\r\nKeistimewaan Balikan terletak pada bunyi petikannya yang khas dan bentuknya yang unik, sehingga menjadikannya ikon alat musik daerah Kalimantan Barat. Balikan biasanya dimainkan sebagai pengiring musik tradisional dan tarian adat, menambah warna serta identitas budaya yang kuat bagi masyarakat Dayak setempat.\r\n\r\nDengan nilai estetika, keunikan suara, dan peranannya dalam kehidupan budaya lokal, Balikan menjadi salah satu simbol kreativitas dan warisan budaya Kalimantan Barat yang terus dijaga hingga kini.', '', 'budaya-indonesia.org', '1759889489_Balikan atau Kurating.webp'),
(20, 22, 'Hadrah', 'Alat musik tradisional Hadrah merupakan hasil perpaduan antara budaya lokal dan budaya Islam di Kalimantan Barat. Hadrah terbuat dari bahan dasar kayu, yang pada bagian tengahnya dilubangi dan dilapisi kulit binatang, sementara di bagian pinggirnya terdapat kerincongan yang menambah nuansa ritmis ketika dimainkan.\r\n\r\nTeknik memainkan Hadrah dilakukan dengan memukul menggunakan jari-jari tangan, sehingga menghasilkan suara khas yang lembut dan ritmis. Alat musik ini kerap digunakan oleh masyarakat Melayu di Kalimantan Barat sebagai pengiring musik Qasidahan maupun dalam berbagai acara keagamaan, menjadi simbol harmoni antara seni, tradisi, dan spiritualitas dalam kehidupan masyarakat setempat.\r\n\r\nDengan karakter bunyi yang unik dan peranannya dalam budaya Islam lokal, Hadrah tetap menjadi salah satu alat musik tradisional yang dilestarikan dan diapresiasi hingga saat ini.', 'https://www.youtube.com/embed/lAD1IZBiS9U', 'budaya-indonesia.org', '1759889551_hadrah.webp'),
(21, 22, 'Entebong', 'Alat musik tradisional Entebong berasal dari Suku Dayak Mualang dan memiliki bentuk yang menyerupai gendang khas Pulau Jawa, termasuk dalam cara memainkannya yang sama, yaitu ditabuh dengan tangan atau alat pemukul. Entebong banyak digunakan oleh masyarakat Kalimantan Barat, terutama di wilayah Kabupaten Sekadau, sebagai pengiring berbagai acara adat dan kesenian tradisional.\r\n\r\nPembuatan Entebong dilakukan oleh masyarakat Suku Dayak setempat, menggunakan bahan kayu untuk badan alat dan kulit hewan untuk permukaannya. Kombinasi bahan ini menghasilkan suara yang khas dan ritmis, sekaligus menunjukkan keterampilan dan kreativitas masyarakat Dayak dalam mengolah bahan alam menjadi alat musik yang bernilai seni tinggi.\r\n\r\nDengan karakter bunyi yang unik dan peranannya dalam upacara serta pertunjukan budaya, Entebong menjadi salah satu simbol identitas budaya masyarakat Dayak Mualang yang terus dijaga dan dilestarikan hingga kini.', 'https://www.youtube.com/embed/PkOXf0_2faM', 'share.google/images', '1759894375_kollatungg.jpeg'),
(22, 22, 'Keledik / Kedire / Kadire', 'Alat musik tradisional Keledik, yang juga dikenal sebagai Korondek oleh masyarakat lokal Rumpun Uut Danum, termasuk dalam jenis alat musik tiup. Alat musik ini umumnya digunakan sebagai pengiring upacara adat, nyanyian tradisional, serta kesenian tari tradisional di Kalimantan Barat.\r\n\r\nPembuatan Keledik memanfaatkan bambu, buah labu yang sudah tua dan berumur 5–6 bulan, serta sarang kelulut, yang secara bersama-sama membentuk alat musik dengan suara khas dan alami. Bunyi yang dihasilkan lembut namun melodius, cocok untuk menambah suasana sakral maupun meriah dalam berbagai acara adat masyarakat Dayak.\r\n\r\nDengan peranannya sebagai pengiring seni dan upacara adat, Keledik menjadi salah satu simbol kearifan lokal dan kreativitas masyarakat Dayak dalam memanfaatkan bahan alam untuk seni musik tradisional yang masih dilestarikan hingga saat ini.', 'https://www.youtube.com/embed/_45opQnzb-M', 'rindiyamfotis.blogspot.com', '1759889850_Keledik (Kedire atau Kadire).webp'),
(23, 22, 'Kollatung', 'Alat musik tradisional Kollatung merupakan salah satu kekayaan budaya masyarakat Dayak di Kalimantan Barat. Alat musik ini dibuat dari logam tembaga atau kuningan, sehingga menghasilkan bunyi yang nyaring dan khas ketika dipukul.\r\n\r\nSecara fungsi, Kollatung tidak jauh berbeda dengan alat musik agung, karena dimainkan dengan cara dipukul untuk menciptakan ritme dan harmoni dalam pertunjukan musik tradisional. Namun, yang membuat Kollatung unik adalah penggunaannya sebagai alat pembayaran dalam hukum adat dan maskawin di masyarakat Dayak, sehingga memiliki nilai ekonomi sekaligus simbolik.\r\n\r\nDengan karakter bunyi yang khas dan peran sosialnya dalam adat, Kollatung menjadi salah satu simbol identitas budaya dan kreativitas masyarakat Dayak yang terus dilestarikan hingga kini.', 'https://www.youtube.com/embed/EL011fNo6a8', 'ibnuasmara.com', '1759894122_Kollatung.webp'),
(24, 22, 'Tar (Tahar)', 'Alat musik tradisional Tahar memiliki asal-usul dari Iran dan dikenal karena bentuk lehernya yang panjang. Tahar termasuk dalam jenis alat musik perkusif mirip tamborin atau rebana, yang menghasilkan bunyi ritmis dan khas.\r\n\r\nAlat musik Tahar biasanya dimainkan pada acara pernikahan atau upacara penyambutan tamu penting, menjadi pengiring yang menambah meriah suasana. Dalam pertunjukannya, kelompok pemain terdiri dari 3 hingga 5 orang, yang secara bersama-sama menciptakan pola ritme harmonis dan enerjik.\r\n\r\nDengan peranannya sebagai pengiring acara penting dan karakter bunyinya yang unik, Tahar menjadi salah satu alat musik tradisional yang menarik dan masih digunakan dalam berbagai kegiatan budaya di Kalimantan Barat.', 'https://www.youtube.com/embed/pB22-xD2xl4', 'budaya-indonesia.org', '1759892845_Tar (Tahar).webp'),
(25, 22, 'Kangkuang', 'Alat musik tradisional Kangkuang berasal dari masyarakat Suku Dayak Banuaka di daerah Kapuas Hulu, Kalimantan Barat. Alat musik ini termasuk dalam jenis gendang tradisional, namun memiliki keunikan tersendiri melalui ukiran khas yang menghiasi permukaannya, menjadikannya mudah dikenali dan sarat nilai seni.\r\n\r\nTeknik memainkan Kangkuang sama seperti gendang pada umumnya, yaitu dengan ditabuh menggunakan telapak tangan kosong tanpa memerlukan alat pemukul khusus. Pola tabuhan yang dihasilkan menciptakan ritme yang khas, sering digunakan sebagai pengiring tarian, upacara adat, maupun kegiatan musik tradisional masyarakat Dayak Banuaka.\r\n\r\nDengan karakter bunyi yang khas dan nilai estetika ukirannya, Kangkuang menjadi salah satu simbol kreativitas dan identitas budaya masyarakat Dayak Banuaka yang terus dijaga hingga saat ini.', 'https://www.youtube.com/embed/0PidV3vnZ5w?si=lV_l-XRUFWy20Ucr', 'Kompas.com', '1759892430_kangkuanggg.png'),
(26, 22, 'Terah Umat', 'Alat musik tradisional Terah Umat merupakan salah satu kekayaan budaya Kalimantan Barat yang fungsinya tidak jauh berbeda dengan gamelan Jawa, yaitu sebagai pengiring musik dan upacara adat. Nama “Umat” berasal dari bahasa daerah setempat yang berarti “besi”, karena alat musik ini dibuat dari besi.\r\n\r\nTeknik memainkan Terah Umat cukup sederhana, yaitu dengan cara dipukul untuk menghasilkan bunyi yang khas dan ritmis. Suara yang dihasilkan oleh alat musik besi ini memberi warna tersendiri dalam pertunjukan musik tradisional Kalimantan Barat, sekaligus menjadi simbol kreativitas masyarakat lokal dalam memanfaatkan bahan alami dan logam untuk seni musik.\r\n\r\nDengan karakter bunyi yang unik dan peranannya dalam berbagai acara adat, Terah Umat tetap dijaga dan dilestarikan oleh masyarakat setempat sebagai bagian dari warisan budaya yang hidup hingga saat ini.', '', 'budaya-indonesia.org', '1759890078_Terah Umat.webp'),
(27, 22, 'Silotong', 'Alat musik tradisional silotong merupakan bagian dari kekayaan budaya Suku Jagoi yang tinggal di Kabupaten Bengkayang, Kalimantan Barat. Alat musik ini dipercaya telah digunakan oleh masyarakat Jagoi sejak masa setelah nenek moyang mereka, sebagai sarana hiburan sekaligus pengiring upacara adat.\r\n\r\nPembuatan silotong dilakukan dengan bahan bambu tori manah basah, jenis bambu asli wilayah Jagoi Babang. Bambu ini memiliki nilai sejarah dan kultural tinggi karena konon telah ditanam secara turun-temurun oleh nenek moyang masyarakat Jagoi hingga generasi saat ini. Pemilihan bambu khusus ini diyakini memengaruhi kualitas suara dan keaslian alat musik silotong.\r\n\r\nNama “silotong” sendiri berasal dari karakter suaranya yang khas, terdengar seperti “tang-ting-tung-tong”. Suara yang dihasilkan alat musik ini menjadikannya cocok sebagai alat musik hiburan, serta pengiring tarian dan syair pada upacara ritual adat setempat. Dengan keunikan suara dan nilai tradisinya, silotong menjadi simbol kreativitas dan warisan budaya Suku Jagoi yang terus dilestarikan hingga kini.', 'https://www.youtube.com/embed/Qo8frvLQvbg?si=uVwek2qaeQ1XGdQV', 'budaya-indonesia.org', '1759890115_Silotong.webp'),
(28, 22, 'Senggayung', 'Salah satu kekayaan budaya Kalimantan Barat yang masih lestari hingga kini adalah alat musik tradisional senggayung, yang termasuk kategori perkusi karena dimainkan dengan cara dipukul. Alat musik ini terbuat dari pasangan bambu yang masing-masing memiliki karakter suara khas, dan banyak ditemui di Kabupaten Ketapang. Senggayung biasanya dimainkan saat musim buah dan panen di ladang, sebagai bentuk rasa syukur sekaligus hiburan masyarakat setempat.\r\n\r\nTeknik memainkan senggayung cukup unik. Pasangan bambu yang memiliki nada rendah dipegang di tangan kiri, sementara pasangan yang bernada tinggi berada di tangan kanan, yang juga berfungsi sebagai pemukul untuk menciptakan ritme harmonis. Perpaduan antara nada rendah dan tinggi menghasilkan musik yang sederhana namun hidup, menambah keseruan dalam tradisi panen maupun perayaan komunitas.\r\n\r\nSelain sebagai hiburan, permainan senggayung juga memiliki peran penting dalam pelestarian budaya dan identitas masyarakat Ketapang. Dengan melibatkan generasi muda untuk belajar dan memainkan alat musik ini, tradisi senggayung diharapkan tetap lestari meski arus modernisasi semakin kuat. Bagi wisatawan dan penikmat budaya, menyaksikan pertunjukan senggayung tidak hanya menghadirkan pengalaman mendengarkan musik yang khas, tetapi juga kesempatan untuk merasakan kedekatan dengan budaya lokal yang hidup dan penuh warna.', 'https://www.youtube.com/embed/sxNAjgKrSac?si=SdcOUZl93QQ03YaI', 'budaya-indonesia.org', '1759890169_senggayung.webp'),
(29, 18, 'Bubur Pedas Khas Pontianak', 'Bubur Pedas merupakan makanan tradisional khas masyarakat Melayu Sambas dan Pontianak, Kalimantan Barat. Makanan ini dikenal tidak hanya karena rasanya gurih dan pedas, tetapi juga karena nilai budaya dan kebersamaan yang terkandung di dalamnya. Bubur Pedas terbuat dari beras yang ditumbuk kasar, lalu dimasak bersama berbagai rempah dan daun aromatik seperti daun kunyit, daun kesum, lengkuas, serai, dan daun salam.\r\n\r\nSelain beras dan rempah, bubur ini dilengkapi dengan sayuran hijau seperti daun pakis, kangkung, bayam, dan kacang panjang, serta tambahan kacang tanah sangrai, ikan teri, atau ayam suwir di atasnya. Rasa pedasnya berasal dari campuran cabai dan lada yang dimasak bersama kuah santan ringan, menghasilkan aroma harum dan cita rasa kaya rempah khas Kalimantan.\r\n\r\nSecara tradisional, Bubur Pedas sering disajikan dalam acara adat dan bulan Ramadan sebagai hidangan berbuka puasa. Masyarakat setempat biasanya memasaknya secara gotong royong dalam jumlah besar untuk dibagikan kepada tetangga dan keluarga, melambangkan semangat kebersamaan dan rasa syukur.\r\n\r\nHingga kini, Bubur Pedas tidak hanya menjadi kuliner rumahan, tetapi juga ikon kuliner daerah Pontianak, banyak dijajakan di pasar tradisional dan acara kebudayaan. Makanan ini menggambarkan kekayaan alam serta kearifan lokal masyarakat Kalimantan Barat dalam mengolah hasil bumi menjadi hidangan yang menyehatkan, lezat, dan penuh makna sosial.', 'https://www.youtube.com/embed/e6j6qcj9Ago', 'Instagram', '1759897906_bubur pedes.jpeg'),
(30, 18, 'Bubur Gunting', 'Bubur Gunting adalah makanan tradisional khas Pontianak, Kalimantan Barat, yang menjadi favorit banyak orang karena rasanya manis, lembut, dan khas. Nama “bubur gunting” berasal dari cara pembuatannya: adonan tepung beras dibentuk panjang, kemudian digunting langsung ke dalam air mendidih hingga potongannya matang dan mengapung. Setelah itu, potongan adonan disajikan dengan kuah santan dan gula merah cair yang kental dan harum.\r\n\r\nCita rasa Bubur Gunting didominasi oleh manis gurih dari gula merah dan santan, sementara teksturnya kenyal lembut mirip bubur candil. Biasanya, makanan ini disajikan hangat sebagai pencuci mulut atau kudapan sore hari. Bubur Gunting banyak dijual di pasar tradisional Pontianak atau di kedai jajanan khas daerah, terutama saat bulan Ramadan sebagai menu takjil.\r\n\r\nSecara budaya, Bubur Gunting mencerminkan akulturasi kuliner antara etnis Melayu dan Tionghoa di Kalimantan Barat. Dari Melayu, ia mendapat pengaruh penggunaan santan dan gula merah; sementara dari Tionghoa, teknik pembentukan adonannya menyerupai makanan manis khas Asia Timur. Perpaduan dua budaya ini menjadikan Bubur Gunting bukan sekadar hidangan lezat, tetapi juga simbol harmoni dan keberagaman kuliner di Kalimantan Barat.', 'https://www.youtube.com/embed/USLUJcrp2PY', 'cookpad.com', '1759897758_bubur guntingg.jpg'),
(31, 18, 'Tempoyak', 'Tempoyak adalah makanan tradisional khas Kalimantan Barat yang dibuat dari fermentasi buah durian. Proses pembuatannya dilakukan dengan cara menyimpan daging durian yang sudah matang di wadah tertutup selama beberapa hari hingga mengalami fermentasi alami. Dari proses ini, daging durian akan berubah menjadi lembut dengan aroma tajam dan rasa asam gurih yang khas.\r\n\r\nTempoyak biasanya digunakan sebagai bumbu masakan, terutama untuk mengolah ikan patin, ikan baung, atau dijadikan sambal tempoyak yang pedas dan harum. Cita rasanya unik, perpaduan antara asam, gurih, dan sedikit manis yang sulit ditemukan pada makanan lain. Dalam budaya masyarakat Melayu Kalimantan Barat, Tempoyak bukan sekadar lauk, tetapi juga simbol kearifan lokal dalam mengolah hasil alam. Saat musim durian tiba, masyarakat memanfaatkan buah yang melimpah agar tidak terbuang percuma dengan cara memfermentasikannya menjadi tempoyak.\r\n\r\nSelain lezat, Tempoyak memiliki nilai gizi tinggi, karena proses fermentasinya menghasilkan probiotik alami yang baik bagi pencernaan. Hingga kini, Tempoyak tetap menjadi bagian penting dari identitas kuliner Kalimantan Barat dan sering disajikan dalam acara adat, jamuan keluarga, maupun sebagai oleh-oleh khas daerah. Keunikan cita rasanya menjadikan Tempoyak bukan hanya makanan, tetapi juga warisan budaya kuliner yang mencerminkan hubungan harmonis masyarakat Kalimantan dengan alam sekitarnya.', 'https://www.youtube.com/embed/RcM8CRqjv0k', 'Pinterest/iStock/detikFood', '1759980862_tempoyak.jpg'),
(32, 18, 'Kerupuk Basah', 'Kerupuk Basah adalah makanan khas Kabupaten Kapuas Hulu, Kalimantan Barat, yang unik karena meskipun disebut kerupuk, teksturnya tidak kering sama sekali. Makanan ini dibuat dari campuran ikan air tawar—biasanya ikan belida, tengadak, atau toman—yang digiling halus, kemudian dicampur dengan tepung sagu dan sedikit bumbu seperti garam serta bawang putih. Adonan ini dibentuk memanjang menyerupai sosis besar, lalu direbus hingga matang, bukan digoreng seperti kerupuk pada umumnya.\r\n\r\nSetelah matang, Kerupuk Basah biasanya disajikan dengan sambal kacang pedas atau sambal asam khas Kapuas Hulu. Teksturnya kenyal dan lembut dengan rasa gurih alami dari ikan sungai. Makanan ini awalnya dibuat oleh masyarakat perbatasan Indonesia–Malaysia sebagai cara sederhana untuk mengolah hasil tangkapan ikan agar lebih tahan lama dan mudah dibawa.\r\n\r\nKini, Kerupuk Basah menjadi ikon kuliner Kapuas Hulu yang sering dijadikan oleh-oleh khas Putussibau. Makanan ini tidak hanya lezat, tetapi juga mencerminkan kehidupan masyarakat pesisir Sungai Kapuas yang sangat bergantung pada hasil perairan mereka. Dalam setiap potongan Kerupuk Basah tersimpan nilai tradisi, kreativitas, dan identitas kuliner masyarakat pedalaman Kalimantan Barat.', 'https://www.youtube.com/embed/ZvcPMsuDjwU', 'detikfinance', '1759981314_kerupuk basah.png'),
(33, 18, 'Pengkang', 'Pengkang adalah makanan tradisional khas Pontianak, Kalimantan Barat, yang terkenal karena aroma harum daun pisang bakarnya dan cita rasa gurih ebi di dalamnya. Makanan ini terbuat dari beras ketan putih yang dimasak setengah matang, kemudian diberi isi ebi (udang kering) yang sudah ditumis dengan bumbu seperti bawang, garam, dan sedikit gula. Setelah itu, adonan ketan dibungkus daun pisang membentuk segitiga atau silinder kecil, lalu dibakar di atas bara api hingga daun pisangnya sedikit gosong dan menebarkan aroma khas yang menggoda.\r\n\r\nRasa Pengkang gurih, sedikit asin, dan memiliki aroma smoky dari proses pembakaran. Biasanya, Pengkang disajikan dengan sambal kerang atau sambal belacan pedas, yang menambah kenikmatan cita rasanya. Makanan ini konon berasal dari daerah Sungai Kakap, Kabupaten Kubu Raya, dan sudah dikenal sejak lama sebagai jajanan tradisional masyarakat pesisir.\r\n\r\nDahulu, Pengkang sering dijadikan bekal perjalanan atau makanan penahan lapar karena tahan lama. Kini, Pengkang menjadi ikon kuliner Pontianak, banyak dijual di sepanjang jalan menuju Mempawah, terutama di kawasan Peniti Luar. Selain lezat, Pengkang juga melambangkan perpaduan budaya antara masyarakat pesisir dan pedalaman Kalimantan Barat, yang sama-sama menghargai hasil alam dari ketan, ebi, hingga daun pisang, dalam satu sajian yang sederhana namun penuh makna.', 'https://www.youtube.com/embed/Us3SRcdqyck', 'Indonesia.go.id', '1759981433_pengkang.png'),
(34, 18, 'Choipan Tjhia', 'Choipan Tjhia, yang sering disebut Chai Kue, adalah salah satu makanan khas Kalimantan Barat yang lahir dari pengaruh budaya Tionghoa Hakka. Hidangan ini berupa kue kukus berbahan dasar tepung beras yang bertekstur lembut dan transparan, berisi tumisan bengkuang, kucai, dan udang kering cincang. Setelah dikukus, Choipan disajikan dengan taburan bawang putih goreng yang renyah serta sambal ebi pedas yang gurih.\r\n\r\nNama “Choipan” berasal dari bahasa Hakka, yaitu “Choi” yang berarti sayur dan “Pan” yang berarti kue. Hidangan ini dibawa oleh perantau Tionghoa Hakka yang menetap di Singkawang dan Pontianak sejak abad ke-18, lalu berakulturasi dengan cita rasa lokal Kalimantan Barat. Kini, Choipan Tjhia menjadi ikon kuliner utama kota Singkawang, bahkan sering dijumpai dalam acara budaya seperti Imlek dan Cap Go Meh.\r\n\r\nSelain lezat, Choipan Tjhia memiliki makna budaya yang dalam. Bagi masyarakat Hakka, makanan ini melambangkan kesederhanaan, kerja keras, dan keberuntungan. Sementara bagi masyarakat Kalimantan Barat secara umum, Choipan menjadi simbol kerukunan antarbudaya, karena keberadaannya mencerminkan perpaduan harmonis antara tradisi Tionghoa dan kuliner lokal Melayu–Dayak.', 'https://www.youtube.com/embed/vvg_W3etlE0', 'Syanti/detikcom', '1759981767_choipan.jpeg'),
(35, 18, 'Pekasam Ikan', 'Pekasam Ikan adalah salah satu makanan tradisional khas Kalimantan Barat yang sudah dikenal sejak zaman dahulu sebagai cara masyarakat setempat mengawetkan ikan secara alami. Makanan ini dibuat dari ikan air tawar, seperti ikan sepat, tengadak, atau belida, yang diawetkan menggunakan garam, beras sangrai, dan asam alami. Proses fermentasi berlangsung selama beberapa hari hingga menghasilkan rasa asam gurih yang khas dan aroma tajam yang menggugah selera.\r\n\r\nAwalnya, Pekasam Ikan dibuat oleh masyarakat pedalaman Kalimantan yang hidup di sepanjang Sungai Kapuas dan tidak memiliki alat pendingin. Dengan teknik fermentasi tradisional, ikan bisa bertahan lama tanpa kehilangan rasa. Biasanya, pekasam digoreng sebelum disajikan agar teksturnya lebih renyah dan aromanya semakin harum. Rasa asam gurihnya berpadu sempurna dengan nasi hangat, menjadikannya lauk favorit banyak keluarga di Kalimantan Barat.\r\n\r\nLebih dari sekadar makanan, Pekasam Ikan mencerminkan kearifan lokal dan kreativitas masyarakat Kalimantan Barat dalam mengolah hasil sungai yang melimpah. Proses pembuatannya yang alami juga menunjukkan hubungan harmonis antara manusia dan alam. Hingga kini, Pekasam tetap menjadi ikon kuliner tradisional yang diwariskan turun-temurun dan menjadi bukti kekayaan budaya kuliner Kalimantan Barat.', 'https://www.youtube.com/embed/q2kqIyS_034', 'detikFood/Sudirman Wamad', '1759982073_pekasam.jpeg'),
(36, 18, 'Lemang', 'Lemang adalah salah satu makanan tradisional khas Kalimantan Barat yang hingga kini masih menjadi bagian penting dari berbagai acara adat dan perayaan masyarakat. Makanan ini terbuat dari beras ketan yang dimasak bersama santan kelapa dan sedikit garam, lalu dimasukkan ke dalam bambu muda yang bagian dalamnya dilapisi daun pisang. Bambu tersebut kemudian dibakar perlahan di atas bara api hingga matang sempurna.\r\n\r\nProses memasak lemang membutuhkan kesabaran dan keterampilan, karena panas api harus dijaga agar lemang matang merata tanpa membuat daun pisang gosong. Hasil akhirnya adalah ketan lembut dengan aroma harum khas bambu dan daun pisang, berpadu sempurna dengan rasa gurih santan. Lemang biasanya disajikan bersama lauk seperti rendang, serundeng, atau sambal, dan sering menjadi hidangan utama dalam perayaan Gawai Dayak, hari besar keagamaan, atau pesta adat Melayu di Kalimantan Barat.\r\n\r\nSelain kelezatannya, lemang memiliki makna simbolis yang mendalam bagi masyarakat setempat. Bambu yang digunakan melambangkan kesederhanaan dan kebersamaan, sementara proses memasaknya secara gotong royong mencerminkan nilai solidaritas dan kekeluargaan. Lemang bukan hanya sekadar makanan, tetapi juga warisan budaya yang menunjukkan keharmonisan antara manusia dan alam di Kalimantan Barat.', 'https://www.youtube.com/embed/iOzBLnW-hnY', 'Jeka Kampai/detikSumut', '1759982306_lemang.jpeg'),
(37, 18, 'Sotong Pengkong', 'Sotong Pengkong adalah makanan khas Kalimantan Barat, terutama berasal dari daerah Pontianak dan sekitarnya. Makanan ini terbuat dari sotong kering (sejenis cumi-cumi) yang dibakar di atas bara api, menghasilkan aroma harum khas laut. Setelah matang, sotong dipipihkan menggunakan alat khusus, proses inilah yang disebut “pengkong” dalam bahasa setempat, yang berarti “dipipihkan” atau “ditekan”.\r\n\r\nSotong Pengkong biasanya disajikan dengan sambal kacang pedas manis yang gurih dan menggugah selera. Teksturnya renyah di luar namun tetap kenyal di dalam, memberikan sensasi unik saat disantap. Dahulu, makanan ini menjadi camilan tradisional para nelayan di pesisir Sungai Kapuas. Kini, Sotong Pengkong menjadi salah satu ikon kuliner jalanan Pontianak, sering dijual di kawasan wisata seperti Jalan Gajah Mada atau di sekitar tepi sungai.\r\n\r\nSelain rasanya yang nikmat, Sotong Pengkong juga mencerminkan identitas kuliner masyarakat pesisir Kalimantan Barat, yang sangat bergantung pada hasil laut. Aroma asap dari pembakarannya serta rasa gurih alami dari sotong menjadikan makanan ini bukan sekadar camilan, tetapi juga bagian dari warisan budaya maritim yang terus dilestarikan.', 'https://www.youtube.com/embed/w6eQl7q3TFk', 'Kementerian Keuangan R', '1759982578_sotong.png'),
(38, 18, 'Tumpi', 'Selain lemang, salah satu makanan khas Kalimantan Barat yang cukup terkenal adalah Kue Tumpi. Kue tradisional ini memiliki bentuk dan rasa yang mirip dengan kue cucur, terbuat dari campuran tepung terigu dan gula merah, yang memberikan warna cokelat keemasan serta rasa manis legit. Adonan Tumpi biasanya ditambahkan sedikit tepung beras dan air, kemudian digoreng dalam minyak panas hingga bagian pinggirnya renyah dan tengahnya lembut kenyal.\r\n\r\nRasa Kue Tumpi yang manis dan legit, berpadu dengan aroma khas gula merah, membuatnya menjadi camilan yang menggoda selera. Teksturnya yang empuk sangat cocok disantap sebagai cemilan sore hari atau teman minum kopi. Dalam tradisi masyarakat Kalimantan Barat, Kue Tumpi sering dihidangkan pada acara adat dan perayaan tertentu, sebagai simbol kebersamaan dan ungkapan rasa syukur.\r\n\r\nHingga kini, Kue Tumpi tetap menjadi bagian penting dari identitas kuliner Kalimantan Barat, mewakili kelezatan sederhana namun kaya akan cita rasa tradisional dan kearifan lokal.', 'https://www.youtube.com/embed/ldm001DvJUY', 'iStock/detikfood', '1759982848_tumpi.jpeg'),
(39, 18, 'Sagu Gunting', 'Sagu Gunting adalah makanan ringan khas Kalimantan Barat yang berbahan dasar sagu, salah satu sumber karbohidrat utama masyarakat pesisir. Nama “gunting” berasal dari cara pembuatannya, di mana adonan sagu yang telah matang digunting menjadi potongan kecil sebelum disajikan.\r\n\r\nTeksturnya kenyal dengan rasa gurih manis, dan biasanya disantap bersama santan atau gula merah cair, menambah kenikmatan cita rasa tradisionalnya. Sagu Gunting tidak hanya sekadar jajanan, tetapi juga mencerminkan budaya masyarakat pesisir Kalimantan yang memanfaatkan sagu sejak dahulu, terutama di daerah yang sulit menanam padi.\r\n\r\nMakanan ini menjadi simbol kemandirian pangan dan identitas kuliner khas Kalimantan Barat, sekaligus mengajarkan nilai kreativitas dan pemanfaatan sumber daya lokal dalam tradisi kuliner masyarakat setempat.', 'https://www.youtube.com/embed/NwKMbCuRWHs', 'youtube', '1759982963_sagu gunting.png'),
(40, 18, 'Kue Kantong Semar', 'Kue Kantong Semar adalah salah satu kudapan khas Kalimantan Barat yang unik dan menarik perhatian karena dibungkus menggunakan tanaman kantong semar, tumbuhan karnivora yang hidup di hutan tropis Kalimantan. Di dalamnya, berisi beras ketan yang dimasak bersama santan dan sedikit garam, kemudian dikukus langsung di dalam kantong semar, sehingga menghasilkan aroma alami dan cita rasa gurih khas hutan tropis.\r\n\r\nDahulu, masyarakat Dayak membuat kue ini sebagai bekal berburu, karena tahan lama dan tidak mudah basi. Selain sebagai makanan, Kue Kantong Semar kini menjadi simbol pelestarian alam dan kearifan lokal masyarakat Kalimantan Barat, menunjukkan bagaimana hasil hutan dapat dimanfaatkan secara kreatif tanpa merusak lingkungan.\r\n\r\nDengan keunikan bahan pembungkusnya dan cita rasa khasnya, Kue Kantong Semar tidak hanya menyajikan pengalaman kuliner, tetapi juga mengajarkan nilai tradisi, kreativitas, dan keberlanjutan bagi masyarakat modern.', 'https://www.youtube.com/embed/FlQXvsVmTkQ', 'youtube', '1759983108_kue kantong semar.png'),
(41, 23, 'Naik Dango', 'Naik Dango adalah upacara adat suku Dayak Kanayatn di Kalimantan Barat yang diselenggarakan sebagai ungkapan syukur kepada Jubata (Tuhan) atas hasil panen padi yang melimpah. Kata “Naik” berarti “menaikkan” atau “mengangkat,” sedangkan “Dango” berarti lumbung padi. Jadi, secara harfiah Naik Dango bermakna mengangkat padi ke lumbung sebagai simbol rasa syukur dan penyimpanan hasil panen untuk masa depan.\r\n\r\nTradisi ini biasanya dilaksanakan pada bulan April, setelah musim panen berakhir. Dalam upacara Naik Dango, masyarakat berkumpul di rumah adat (balai) untuk membawa berbagai hasil panen seperti padi, umbi, buah, dan sayur. Mereka juga menyajikan makanan tradisional seperti lemang, tempoyak, kue kantong semar, dan tumpi sebagai bagian dari perayaan. Tarian adat, musik gong, nyanyian ritual, serta doa kepada Jubata dipersembahkan sebagai bentuk penghormatan dan rasa syukur.\r\n\r\nNaik Dango bukan sekadar pesta panen, melainkan juga momen penting bagi masyarakat Dayak untuk memperkuat persaudaraan, gotong royong, dan pelestarian budaya leluhur. Perayaan ini mencerminkan hubungan yang harmonis antara manusia, alam, dan Sang Pencipta. Hingga kini, tradisi Naik Dango masih terus dilestarikan dan bahkan telah menjadi agenda budaya tahunan tingkat provinsi yang menarik wisatawan lokal maupun mancanegara.', 'https://www.youtube.com/embed/dc0aJaG_2J4?si=0IHf_GFIEHoUttqs', 'Kompas.com', '1760627856_Naik Dango.jpeg'),
(42, 23, 'Bemanang', 'Bemanang adalah ritual adat khas Suku Dayak di Kalimantan Barat yang biasanya dilakukan sebagai doa syukur dan permohonan keselamatan dalam berbagai aspek kehidupan masyarakat. Ritual ini erat kaitannya dengan kegiatan berburu, panen, atau upacara adat tertentu, dan bertujuan untuk memohon berkat dari Jubata (Tuhan) atau roh leluhur agar segala kegiatan berjalan lancar dan aman.\r\n\r\nProsesi Bemanang dipimpin oleh tokoh adat atau pemimpin spiritual, yang melantunkan doa-doa khusus sambil memberikan arahan kepada anggota masyarakat yang terlibat. Persembahan simbolis, seperti ayam, ketan, sirih, atau benda-benda khas lokal, biasanya digunakan sebagai bagian dari ritual untuk menyampaikan permohonan kepada dunia roh.\r\n\r\nRitual ini bukan hanya sarana spiritual, tetapi juga media penguatan sosial dan budaya, karena seluruh komunitas terlibat dan ikut menjaga nilai-nilai kebersamaan, gotong royong, serta penghormatan terhadap alam dan leluhur. Bemanang mencerminkan kearifan lokal masyarakat Dayak Kalimantan Barat dalam menjaga keseimbangan antara manusia, alam, dan dunia gaib, sekaligus memperkuat identitas budaya yang diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/rPaV7ZujoHA?si=kVC059UGJ7dvEd7w', 'instagram.com', '1760630226_Bemanang.jpeg'),
(43, 23, 'Ikat Tongang', 'Ikat Tongang adalah upacara adat khas Suku Dayak di Kalimantan Tengah, khususnya di Kabupaten Lamandau. Upacara ini bertujuan untuk menyambut tamu penting secara adat, mendoakan keselamatan mereka, dan sekaligus menjadi simbol ikatan persatuan dan kesatuan dalam komunitas.\r\n\r\nProsesi Ikat Tongang melibatkan pengikatan gelang (tongang) yang terbuat dari akar kayu pada pergelangan tangan tamu yang hadir. Pengikatan ini biasanya dipimpin oleh kepala adat atau tokoh masyarakat yang berwenang, disertai doa-doa dan pantun adat sebagai ungkapan selamat datang dan permohonan berkat. Gelang tongang diyakini membawa perlindungan, keberkahan, dan mempererat hubungan sosial antara tamu dan masyarakat lokal.\r\n\r\nUpacara ini bukan hanya ritual simbolis, tetapi juga media penguatan nilai-nilai sosial, gotong royong, dan penghormatan terhadap tamu. Ikat Tongang mencerminkan kearifan lokal Suku Dayak dalam membina hubungan harmonis antarindividu dan menjaga tradisi adat yang kaya makna.', 'https://www.youtube.com/embed/SWsGGp4WUHY?si=NHO3btxAxuelWXSB', 'watchdoc.co.id', '1760630086_ikat tonggang.jpeg'),
(44, 23, 'Tepung Tawar', 'Tepung Tawar adalah salah satu ritual adat yang dijalankan oleh Suku Dayak di Kalimantan Barat sebagai bentuk upacara penyucian dan doa keselamatan. Ritual ini dilakukan dengan menggunakan tepung beras atau tepung khusus yang dipercikkan ke orang, hewan, rumah, atau benda-benda tertentu sebagai simbol pembersihan, perlindungan, dan keberkahan.\r\n\r\nUpacara Tepung Tawar biasanya dipimpin oleh tokoh adat atau pemimpin spiritual yang berpengalaman. Dalam prosesi ritual, tokoh adat melantunkan doa-doa khusus sambil menyiramkan atau menaburkan tepung ke objek yang dimaksud, disertai persembahan simbolis seperti sirih, kapur, ayam, atau ketan.\r\n\r\nRitual ini dilakukan dalam berbagai momen penting, seperti pesta adat, pernikahan, pindah rumah, panen, atau memulai kegiatan besar lainnya, sebagai wujud syukur dan permohonan perlindungan dari Jubata (Tuhan) dan roh leluhur. Tepung Tawar tidak hanya memiliki makna spiritual, tetapi juga menjadi sarana penguatan ikatan sosial, karena seluruh anggota masyarakat terlibat dalam prosesi ini.\r\n\r\nTepung Tawar mencerminkan kearifan lokal masyarakat Dayak dalam menjaga hubungan harmonis antara manusia, alam, dan dunia gaib, serta menegaskan nilai rasa hormat, gotong royong, dan rasa syukur dalam setiap aspek kehidupan.', 'https://www.youtube.com/embed/veWkYGcpGic?si=nrQ8PEY0q6DmfS9n', 'porosbumi.pandutani.or.id', '1760629969_Tepung Tawar.jpg'),
(45, 23, 'Ngabahu Tiak', 'Ngabahu Tiak adalah ritual adat yang dijalankan oleh beberapa kelompok Suku Dayak di Kalimantan Barat, terutama yang tinggal di wilayah pedalaman. Ritual ini bertujuan untuk memohon keselamatan, keberkahan, dan perlindungan dari Jubata (Tuhan) maupun roh leluhur sebelum memulai kegiatan tertentu yang penting bagi masyarakat, seperti berburu, menangkap ikan, atau melakukan perjalanan jauh.\r\n\r\nRitual Ngabahu Tiak dipimpin oleh tokoh adat atau pemimpin spiritual yang berpengalaman, yang melantunkan doa-doa khusus serta memberikan arahan kepada anggota masyarakat yang mengikuti ritual. Persembahan dalam ritual ini biasanya berupa hewan, sirih, ketan, atau bahan simbolis lainnya, sebagai tanda hormat dan permohonan kepada dunia roh.\r\n\r\nNgabahu Tiak bukan sekadar praktik spiritual, tetapi juga media penguatan sosial dan budaya, karena seluruh anggota komunitas terlibat dalam prosesi ini. Ritual ini mencerminkan kearifan lokal Suku Dayak dalam menjaga keseimbangan antara manusia, alam, dan alam gaib, serta menegaskan nilai gotong royong, hormat, dan rasa syukur dalam kehidupan sehari-hari.', 'https://www.youtube.com/embed/QzXqGkn-g0I?si=JEMthqgrH9WTJzHa', 'aman.or.id', '1760629863_Ngabahu Tiak.jpg'),
(46, 23, 'Nyangahatn', 'Nyangahatn adalah salah satu ritual adat penting bagi Suku Dayak Kanayatn di Kalimantan Barat. Ritual ini berisi doa syukur dan permohonan kepada Jubata (Tuhan) untuk memohon berkat, keselamatan, dan kelancaran dalam berbagai aspek kehidupan. Kegiatan yang biasanya diiringi Nyangahatn meliputi berladang, pernikahan, pindah rumah, kelahiran anak, hingga momen-momen penting lainnya dalam komunitas.\r\n\r\nRitual ini dipimpin oleh seorang Panyangahtn, tokoh adat yang memiliki pengetahuan spiritual dan kewenangan untuk melantunkan doa-doa. Doa-doa tersebut diiringi dengan persembahan berupa ayam, kapur, sirih, ketan, dan bahan-bahan simbolis lainnya, yang diyakini sebagai sarana untuk menyampaikan permohonan kepada Jubata.\r\n\r\nNyangahatn bukan hanya sekadar ritual spiritual, tetapi juga menjadi wadah pembinaan sosial dan budaya, memperkuat rasa kebersamaan antaranggota komunitas, sekaligus menjaga hubungan harmonis antara manusia, alam, dan Tuhan. Ritual ini mencerminkan kearifan lokal Suku Dayak Kanayatn yang menekankan syukur, kehati-hatian, dan penghormatan terhadap kehidupan dalam setiap aktivitas sehari-hari.', 'https://www.youtube.com/embed/BGW0hxBvIc0?si=344-MP_orZo63oVl', 'kalbar.harianhaluan.com', '1760629754_Nyangahatn.jpeg'),
(47, 23, 'Manajah Antang', 'Manajah Antang adalah salah satu ritual adat khas suku Dayak di Kalimantan Barat yang bertujuan untuk memanggil dan meminta petunjuk dari roh leluhur atau alam gaib. Ritual ini dilakukan melalui perantaraan burung Antang (elang), yang dianggap sebagai perantara antara dunia manusia dan dunia roh.\r\n\r\nTradisi Manajah Antang dijalankan dalam berbagai situasi penting. Misalnya, untuk mendapatkan informasi tentang lokasi musuh saat perang, meminta petunjuk dalam pengambilan keputusan kehidupan, menjamin keselamatan dalam perjalanan, atau membantu masyarakat menghadapi kesulitan dan tantangan tertentu. Proses ritual biasanya melibatkan pemimpin adat atau tetua suku Dayak yang memiliki pengetahuan spiritual mendalam, disertai doa, sesaji, dan pengamatan terhadap perilaku burung Antang.\r\n\r\nManajah Antang bukan sekadar ritual mistis, tetapi juga mencerminkan kearifan lokal masyarakat Dayak dalam menjalin hubungan harmonis dengan alam dan leluhur. Praktik ini menjadi bagian penting dari identitas budaya suku Dayak, sekaligus sarana melestarikan nilai-nilai spiritual, sosial, dan tradisi komunitas dari generasi ke generasi.', 'https://www.youtube.com/embed//mKAOpNW6aSE?si=ZOLeSx5JpChfKs4N', 'koropak.co.id', '1760629635_Manajah Antang.jpeg'),
(48, 23, 'Batalah', 'Batalah adalah upacara adat pemberian nama bayi yang baru lahir dalam budaya masyarakat Dayak di Kalimantan Barat. Upacara ini biasanya dilaksanakan ketika bayi berusia 3 hingga 7 hari, tergantung kemampuan ekonomi keluarga. Tradisi ini memiliki makna spiritual yang dalam, karena melalui Batalah, keluarga tidak hanya menamai bayi, tetapi juga memohon perlindungan dan berkat dari Sang Pencipta, yang dalam kepercayaan Dayak disebut Jubata.\r\n\r\nDalam pelaksanaannya, seorang dukun adat atau tetua akan membacakan mantra-mantra khusus untuk memberikan nama pada bayi. Nama yang diberikan sering kali memiliki makna tertentu, misalnya harapan agar bayi tumbuh sehat, kuat, dan cerdas. Selama upacara, keluarga dan kerabat berkumpul, membawa persembahan tradisional berupa makanan, minuman, atau barang simbolik sebagai tanda syukur.\r\n\r\nBatalah bukan hanya sekadar ritual, tetapi juga merupakan wujud identitas budaya dan ikatan sosial dalam masyarakat Dayak. Upacara ini memperkuat hubungan keluarga, komunitas, dan spiritual, sekaligus menjadi cara melestarikan warisan budaya yang telah diwariskan turun-temurun.', 'https://www.youtube.com/embed/S9pYgBbB5PI?si=4A8eRTB2S4txv5ds', 'Jurnal Untan', '1760629477_batalah.jpeg'),
(49, 23, 'Robo-Robo', 'Robo-Robo adalah salah satu upacara adat khas Kalimantan Barat, khususnya masyarakat Melayu di daerah Pontianak dan sekitarnya. Upacara ini biasanya digelar setelah musim panen atau menjelang perayaan tertentu sebagai bentuk rasa syukur kepada Tuhan atas rezeki yang diberikan. Nama “Robo-Robo” sendiri berasal dari kata lokal yang menggambarkan suasana ramai, penuh kegembiraan, dan kebersamaan masyarakat saat melaksanakan prosesi adat.\r\n\r\nDalam pelaksanaannya, Robo-Robo melibatkan berbagai ritual, termasuk doa, tarian, nyanyian tradisional, dan pertunjukan musik Melayu. Masyarakat berkumpul di tepi sungai atau lapangan terbuka, membawa hasil bumi dan makanan tradisional untuk dipersembahkan. Upacara ini tidak hanya bertujuan sebagai ungkapan syukur, tetapi juga memperkuat ikatan sosial, mengajarkan gotong royong, serta mewariskan nilai-nilai budaya dari generasi ke generasi.\r\n\r\nSelain aspek religius dan sosial, Robo-Robo juga menjadi atraksi budaya bagi wisatawan yang ingin mengenal lebih jauh tradisi Melayu Kalimantan Barat. Warna-warni pakaian adat, alunan musik tradisional, dan kelezatan kuliner lokal yang disajikan saat acara membuat Robo-Robo tidak sekadar ritual, tetapi juga representasi kekayaan budaya dan identitas masyarakat Kalbar.', 'https://www.youtube.com/embed/m5eCi6BILEk', 'pontianakinfo.disway.id', '1760629489_Robo-Robo.jpeg'),
(50, 23, 'Gawai Dayak', 'Gawai Dayak adalah perayaan adat terbesar masyarakat Dayak di Kalimantan Barat yang diadakan setiap tahun sebagai ungkapan syukur atas hasil panen padi. Kata “gawai” dalam bahasa Dayak berarti pesta atau perayaan, sehingga Gawai Dayak dapat diartikan sebagai “pesta panen” yang menggambarkan rasa terima kasih masyarakat kepada Petara (Tuhan) atas berkat dan kesuburan tanah.\r\n\r\nPerayaan ini biasanya berlangsung pada akhir bulan Mei atau awal Juni dan dipusatkan di Pontianak, namun juga dilaksanakan di berbagai daerah pedalaman Kalimantan Barat. Selama perayaan Gawai Dayak, masyarakat mengenakan pakaian adat berhias manik-manik, bulu burung enggang, dan kain tradisional tenun Dayak. Berbagai kegiatan digelar seperti tarian adat, nyanyian rakyat, ritual adat, pameran seni, hingga lomba masakan tradisional Dayak.\r\n\r\nSelain sebagai bentuk rasa syukur, Gawai Dayak juga berfungsi mempererat hubungan antar-suku Dayak, sekaligus melestarikan warisan leluhur di tengah arus modernisasi. Makanan tradisional seperti lemang, tuak, tempoyak, dan daging babi hutan asap sering dihidangkan sebagai bagian dari pesta. Dalam konteks budaya, Gawai Dayak bukan sekadar festival, melainkan identitas kolektif masyarakat Kalimantan Barat yang menjunjung tinggi nilai gotong royong, rasa syukur, dan hubungan harmonis dengan alam.\r\n\r\nKini, Gawai Dayak telah berkembang menjadi agenda wisata budaya tahunan yang menarik wisatawan dari dalam dan luar negeri. Perayaan ini menjadi simbol kebanggaan etnis Dayak dan bukti kekayaan budaya Kalimantan Barat yang beragam namun tetap bersatu dalam semangat kebersamaan.', 'https://www.youtube.com/embed/4rJ2FycWuc8?si=fpi6VhA4PYJbqaCD', 'antaranews.com', '1760629079_Gawai Dayak.jpg'),
(52, 20, 'Mandau', 'Mandau adalah salah satu senjata tradisional paling terkenal di Kalimantan Barat, terutama milik masyarakat Dayak. Mandau merupakan golok atau pedang panjang dengan bilah yang tajam dan sedikit melengkung, dirancang untuk berperang, berburu, maupun pertahanan diri. Gagang Mandau biasanya terbuat dari kayu keras, tanduk, atau gading, sering dihias dengan ukiran khas Dayak dan motif leluhur, sementara bilahnya terbuat dari besi atau baja pilihan, yang bisa sangat tajam dan tahan lama.\r\n\r\nSelain fungsinya sebagai senjata, Mandau memiliki makna simbolis yang mendalam. Dalam budaya Dayak, Mandau dianggap sebagai simbol keberanian, kehormatan, dan status sosial pemiliknya. Senjata ini sering muncul dalam upacara adat, tarian perang, pertunjukan budaya, bahkan diwariskan secara turun-temurun sebagai warisan keluarga dan simbol identitas suku.\r\n\r\nKeunikan Mandau terletak pada teknik pembuatannya, yang membutuhkan keterampilan tinggi pengrajin lokal. Bilah harus diasah dengan presisi, gagang dihias dengan ukiran yang bermakna, dan keseimbangan senjata dijaga agar efektif digunakan. Beberapa Mandau juga memiliki sarung khusus yang dihias dengan manik-manik, bulu, atau bahan alam lain sebagai tambahan simbolisme budaya.\r\n\r\nHingga kini, Mandau tetap menjadi ikon budaya dan warisan sejarah masyarakat Dayak di Kalimantan Barat, tidak hanya sebagai senjata perang, tetapi juga sebagai karya seni tradisional yang mencerminkan keberanian, keterampilan, dan nilai-nilai budaya lokal yang dilestarikan dari generasi ke generasi.', 'https://www.youtube.com/embed/8vnv89hRkGI', 'pariwisataindonesia.id', 'item_52_1760894384.jpeg'),
(53, 20, 'Ambang / Parang Ilang', 'Ambang, yang juga dikenal sebagai Parang Ilang, adalah salah satu senjata tradisional khas Kalimantan Barat, khususnya milik masyarakat Melayu dan Dayak. Bentuknya menyerupai golok panjang dengan bilah lebar dan tajam, dirancang untuk memotong, menebas, maupun bertahan dalam pertempuran. Gagang Ambang biasanya terbuat dari kayu keras atau bahan alami lain, sementara bilahnya terbuat dari besi atau baja pilihan, kadang dihias dengan ukiran tradisional yang menunjukkan identitas dan status pemiliknya.\r\n\r\nSelain sebagai senjata, Ambang/Parang Ilang juga memiliki makna simbolis dan budaya. Dalam tradisi masyarakat setempat, senjata ini dianggap sebagai simbol keberanian, kekuatan, dan kehormatan. Ambang kerap digunakan dalam upacara adat, pertunjukan tari perang, atau demonstrasi budaya, sekaligus menjadi lambang identitas dan martabat pemiliknya.\r\n\r\nKeunikan Ambang terletak pada teknik pembuatannya, yang memerlukan keterampilan tinggi dari pengrajin lokal untuk menajamkan bilah, membuat gagang yang kuat, dan memastikan keseimbangan senjata. Setiap Ambang dapat memiliki karakteristik tersendiri, baik dari panjang, lebar bilah, maupun motif ukirannya, yang membedakannya dari golok atau parang tradisional lain di Indonesia.\r\n\r\nHingga kini, Ambang/Parang Ilang tetap menjadi ikon budaya dan warisan sejarah masyarakat Kalimantan Barat, tidak hanya sebagai senjata, tetapi juga sebagai karya seni tradisional yang mencerminkan keberanian, identitas, dan nilai-nilai budaya lokal yang diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/F0fI7SDHMiw', 'youtube', 'item_53_1760894097.jpeg'),
(54, 20, 'Talawang / Telawang', 'Talawang, yang juga dikenal sebagai Telawang, adalah salah satu senjata tradisional khas Kalimantan Barat, terutama milik masyarakat Dayak. Senjata ini berbentuk perisai kecil dan memanjang yang biasanya dibuat dari kayu keras atau kulit binatang, kadang dihias dengan ukiran khas Dayak yang penuh simbolisme budaya. Talawang berfungsi sebagai alat pertahanan diri, digunakan untuk menangkis serangan senjata lawan dalam pertempuran atau peperangan tradisional.\r\n\r\nSelain fungsinya sebagai alat perlindungan, Talawang memiliki nilai budaya dan simbolis. Di masyarakat Dayak, Talawang dianggap sebagai simbol keberanian, kehormatan, dan identitas suku. Senjata ini sering muncul dalam upacara adat, pertunjukan tari perang, atau demonstrasi budaya, menampilkan keindahan sekaligus kekuatan simbolik masyarakat Dayak.\r\n\r\nKeunikan Talawang terletak pada bahan, bentuk, dan hiasannya, yang dibuat dengan keterampilan tinggi oleh pengrajin lokal. Ukiran pada Talawang biasanya mengandung motif binatang, alam, atau simbol leluhur, yang menunjukkan hubungan erat antara manusia dan alam. Selain itu, Talawang juga dirancang agar ringan namun kokoh, sehingga efektif digunakan dalam pertahanan dan mudah dibawa dalam pertempuran.\r\n\r\nHingga kini, Talawang tetap menjadi ikon budaya dan warisan sejarah masyarakat Dayak di Kalimantan Barat, tidak hanya sebagai perisai, tetapi juga sebagai karya seni tradisional yang mencerminkan identitas, keberanian, dan nilai-nilai budaya lokal yang diwariskan secara turun-temurun.', 'https://www.youtube.com/embed/GSkFvFPxBIo', 'Validnews.id', 'item_54_1760893937.jpeg');
INSERT INTO `isi_kategori` (`id`, `kategori_id`, `nama_item`, `deskripsi`, `link`, `sumber_foto`, `foto`) VALUES
(55, 20, 'Sumpit', 'Sumpit adalah salah satu senjata tradisional khas masyarakat Dayak di Kalimantan Barat, yang digunakan sebagai alat berburu. Sumpit terbuat dari tabung panjang berbahan kayu atau bambu, yang berfungsi untuk menembakkan panah atau peluru kecil beracun. Senjata ini memanfaatkan teknik tiupan, di mana pemburu meniupkan peluru melalui tabung dengan kekuatan dan arah yang tepat untuk mengenai sasaran.\r\n\r\nSelain fungsinya sebagai alat berburu, Sumpit juga memiliki nilai budaya dan simbolik. Dalam beberapa komunitas Dayak, Sumpit dianggap sebagai simbol keterampilan, kesabaran, dan keberanian para pemburu. Senjata ini kerap digunakan dalam upacara adat, pertunjukan budaya, atau kompetisi berburu tradisional, sekaligus menjadi simbol identitas suku Dayak.\r\n\r\nKeunikan Sumpit terletak pada bahan, ukuran, dan teknik pembuatannya, yang memerlukan keterampilan tinggi dari pengrajin lokal. Tabung sumpit harus dirancang agar ringan, kuat, dan tepat sasaran, sementara pelurunya kadang diberi racun alami dari tumbuhan untuk berburu hewan. Setiap sumpit dapat memiliki desain khas tersendiri, mulai dari panjang, ketebalan, hingga hiasan ukir pada permukaan tabung, sehingga mencerminkan asal-usul budaya pembuatnya.\r\n\r\nHingga kini, Sumpit tetap menjadi ikon budaya dan warisan tradisional masyarakat Dayak di Kalimantan Barat, tidak hanya sebagai alat berburu, tetapi juga sebagai karya seni dan simbol identitas suku yang terus dipelihara dari generasi ke generasi.', 'https://www.youtube.com/embed/xNvlmzxCouI', 'detikcom', 'item_55_1760893823.jpeg'),
(56, 20, 'Tombak / Lonjo', 'Tombak, yang juga dikenal dengan sebutan Lonjo, adalah salah satu senjata tradisional khas Kalimantan Barat yang digunakan oleh masyarakat Melayu dan Dayak sebagai alat perang, berburu, dan pertahanan diri. Tombak Lonjo terdiri dari bilah tajam yang panjang dan tangkai kayu kuat, dirancang agar dapat dilempar maupun digunakan untuk menusuk secara langsung. Bagian bilah biasanya terbuat dari besi atau baja, sedangkan gagangnya dari kayu keras, kadang dihias dengan ukiran khas atau ornamen tradisional.\r\n\r\nSelain fungsi praktis, Tombak/Lonjo juga memiliki nilai simbolis. Senjata ini dianggap sebagai simbol keberanian, keterampilan, dan martabat. Dalam beberapa komunitas, Tombak/Lonjo diwariskan turun-temurun sebagai warisan keluarga dan simbol status sosial. Senjata ini juga digunakan dalam upacara adat, pertunjukan budaya, dan tarian perang tradisional, menunjukkan keindahan sekaligus kekuatan budaya lokal.\r\n\r\nKeunikan Tombak/Lonjo terletak pada teknik pembuatannya, yang memerlukan keterampilan tinggi dari pengrajin untuk memastikan bilah tajam, gagang kuat, dan keseimbangan senjata. Setiap tombak dapat memiliki karakteristik tersendiri, baik dari panjang, bentuk bilah, maupun hiasan pada gagangnya, sehingga berbeda antara satu daerah dengan daerah lainnya.\r\n\r\nHingga kini, Tombak/Lonjo tetap menjadi ikon budaya dan warisan sejarah masyarakat Kalimantan Barat, tidak hanya sebagai senjata, tetapi juga sebagai karya seni tradisional yang mencerminkan identitas, keberanian, dan nilai-nilai budaya lokal yang terus dipertahankan.', 'https://www.youtube.com/embed/Gs_uxmVKmhg', '1001indonesia.net', 'item_56_1760893698.jpeg'),
(57, 20, 'Dohong', 'Dohong adalah salah satu senjata tradisional khas Kalimantan Barat, yang digunakan oleh masyarakat Melayu dan Dayak sebagai alat pertahanan diri dan senjata perang. Bentuk Dohong menyerupai belati atau golok pendek dengan bilah tajam dan gagang yang terbuat dari kayu keras, tanduk, atau bahan alami lainnya. Bilah Dohong biasanya lurus atau sedikit melengkung, dirancang agar mudah digunakan untuk pertempuran jarak dekat.\r\n\r\nSelain fungsinya sebagai senjata, Dohong memiliki nilai simbolis dan budaya. Senjata ini sering dianggap sebagai simbol keberanian, kehormatan, dan martabat pemiliknya, serta sering digunakan dalam upacara adat, pertunjukan budaya, atau tari perang tradisional. Beberapa komunitas juga mewariskan Dohong dari generasi ke generasi sebagai warisan keluarga dan simbol status sosial.\r\n\r\nKeunikan Dohong terletak pada teknik pembuatannya, yang membutuhkan keterampilan tinggi dari pengrajin lokal untuk menajamkan bilah, menghias gagang dengan ukiran tradisional, dan menjaga keseimbangan senjata. Setiap Dohong dapat memiliki ciri khas tersendiri, baik dari bentuk bilah, panjang, maupun motif ukirannya, yang mencerminkan asal-usul budaya daerah tersebut.\r\n\r\nHingga kini, Dohong tetap menjadi ikon budaya dan warisan sejarah masyarakat Kalimantan Barat, tidak hanya sebagai senjata, tetapi juga sebagai karya seni tradisional yang mencerminkan identitas, keberanian, dan nilai-nilai budaya lokal yang diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/Cs5yKRDl-WY', 'Wikipedia', 'item_57_1760893542.jpeg'),
(58, 20, 'Podang', 'Podang adalah salah satu senjata tradisional khas Kalimantan Barat, yang biasa digunakan oleh masyarakat Melayu dan beberapa suku Dayak sebagai alat perang dan pertahanan diri. Bentuk Podang menyerupai pedang pendek atau golok dengan bilah lurus, biasanya memiliki panjang sedang, tajam, dan seimbang agar mudah digunakan dalam pertempuran jarak dekat. Gagang Podang umumnya terbuat dari kayu keras, tanduk, atau bahan alami lainnya, sering dihias dengan ukiran tradisional yang menunjukkan identitas budaya dan status sosial pemiliknya.\r\n\r\nSelain fungsi praktis sebagai senjata, Podang juga memiliki makna simbolis. Dalam tradisi masyarakat setempat, Podang dianggap sebagai simbol keberanian, kehormatan, dan martabat. Senjata ini sering digunakan dalam upacara adat, pertunjukan budaya, atau tarian perang tradisional, sekaligus menjadi lambang identitas komunitas dan keberanian prajurit Melayu atau Dayak.\r\n\r\nKeunikan Podang terletak pada teknik pembuatannya, di mana pengrajin lokal harus menguasai keterampilan menajamkan bilah, mengukir gagang, dan menjaga keseimbangan senjata. Setiap Podang dapat memiliki karakteristik tersendiri, baik dari bentuk bilah, ukuran, maupun hiasan ukirannya, yang membedakannya dari senjata tradisional daerah lain di Indonesia.\r\n\r\nHingga kini, Podang tetap menjadi ikon budaya dan warisan sejarah masyarakat Kalimantan Barat, tidak hanya sebagai senjata, tetapi juga sebagai karya seni tradisional yang mencerminkan identitas, keberanian, dan nilai-nilai budaya lokal yang diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/LRH0sxT9HLg', 'youtube/@BORNEO-ART TV', 'item_58_1760893430.jpeg'),
(59, 20, 'Bilah', 'Bilah adalah salah satu senjata tradisional khas Kalimantan Barat, yang umum digunakan oleh masyarakat Melayu dan Dayak sebagai alat perang dan pertahanan diri. Bentuk Bilah menyerupai pedang atau golok dengan bilah lurus dan tajam, biasanya memiliki panjang sedang dan gagang yang terbuat dari kayu keras, tanduk, atau bahan alami lainnya. Bilah sering dihias dengan ukiran atau ornamen khas yang menunjukkan asal-usul budaya dan status pemiliknya.\r\n\r\nSelain fungsi praktis sebagai senjata, Bilah juga memiliki nilai simbolis. Dalam tradisi masyarakat setempat, Bilah dianggap sebagai simbol keberanian, kehormatan, dan martabat. Senjata ini sering digunakan dalam upacara adat, pertunjukan budaya, atau tarian perang tradisional, sekaligus sebagai lambang identitas dan kekuatan komunitas.\r\n\r\nKeunikan Bilah terletak pada teknik pembuatannya, di mana pengrajin lokal memerlukan keterampilan tinggi untuk menajamkan bilah, mengukir gagang, dan memastikan keseimbangan senjata. Setiap Bilah dapat memiliki karakteristik tersendiri, mulai dari bentuk, panjang, hingga hiasan ukirannya, sehingga berbeda antara satu daerah dengan daerah lainnya.\r\n\r\nHingga kini, Bilah tetap menjadi ikon budaya dan kebanggaan masyarakat Kalimantan Barat, tidak hanya sebagai senjata, tetapi juga karya seni tradisional dan warisan budaya yang diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/60LldBhpIfM', 'selasar.com', 'item_59_1760893157.jpg'),
(60, 20, 'Gayang', 'Gayang adalah salah satu senjata tradisional khas masyarakat Melayu dan Dayak di Kalimantan Barat yang berfungsi sebagai senjata perang dan alat pertahanan diri. Bentuk Gayang menyerupai golok pendek atau pedang kecil, dengan bilah lurus atau sedikit melengkung dan tajam. Gagangnya terbuat dari kayu keras atau tanduk, sering dihias dengan ukiran tradisional yang mencerminkan simbolisme budaya setempat.\r\n\r\nSelain sebagai senjata, Gayang juga memiliki makna budaya dan adat. Dalam masyarakat Melayu dan beberapa suku Dayak, Gayang dianggap sebagai simbol keberanian, kehormatan, dan status sosial. Senjata ini kerap digunakan dalam upacara adat, pertunjukan budaya, atau tari perang tradisional, menampilkan keindahan sekaligus kekuatan masyarakat Kalimantan Barat.\r\n\r\nTeknik pembuatan Gayang memerlukan keterampilan tinggi dari pengrajin lokal. Setiap bilah dipoles dan diasah secara teliti agar memiliki ketajaman optimal, sementara gagangnya dihias dengan ornamen khas yang berbeda-beda sesuai asal-usulnya. Keunikan ini membuat Gayang tidak hanya sebagai senjata, tetapi juga sebagai karya seni tradisional yang memiliki nilai sejarah dan estetika tinggi.\r\n\r\nHingga kini, Gayang tetap menjadi ikon budaya dan identitas lokal di Kalimantan Barat. Senjata ini tidak hanya dipelihara sebagai warisan budaya, tetapi juga menjadi koleksi tradisional dan simbol kebanggaan masyarakat, menunjukkan hubungan erat antara masyarakat dan nilai-nilai tradisi mereka.', 'https://www.youtube.com/embed/xeM3d4PC0Xs', 'swarawarta.co.id', 'item_60_1760892907.jpg'),
(61, 20, 'Parang Melayu', 'Parang Melayu adalah salah satu senjata tradisional khas Kalimantan Barat yang memiliki makna sejarah dan budaya yang dalam. Senjata ini biasanya digunakan oleh masyarakat Melayu sebagai alat pertahanan diri, alat perang, maupun simbol status sosial. Bentuk Parang Melayu menyerupai golok atau sabit dengan bilah melengkung dan tajam, sedangkan gagangnya terbuat dari kayu keras atau tanduk, dihias dengan ukiran atau ornamen khas Melayu.\r\n\r\nParang Melayu tidak hanya berfungsi sebagai senjata, tetapi juga memiliki nilai simbolik dan estetika. Di beberapa komunitas Melayu, Parang Melayu dianggap sebagai warisan keluarga yang diturunkan dari generasi ke generasi. Senjata ini sering digunakan dalam upacara adat, pertunjukan budaya, atau tarian tradisional, seperti tari perang Melayu, sebagai simbol keberanian dan kehormatan.\r\n\r\nKeunikan Parang Melayu terletak pada teknik pembuatan dan desain bilahnya, yang menuntut keterampilan tinggi dari pengrajin. Setiap parang bisa memiliki ciri khas tersendiri, baik dari bentuk, ukuran, maupun hiasan ukirannya, yang membedakannya dari parang daerah lain di Indonesia.\r\n\r\nHingga kini, Parang Melayu tetap menjadi ikon budaya Melayu di Kalimantan Barat, selain digunakan dalam kegiatan adat, juga menjadi koleksi budaya dan souvenir tradisional yang merepresentasikan identitas dan sejarah masyarakat Melayu di daerah ini.', 'https://www.youtube.com/embed/l82LNh5zHy4', 'Wikipedia', 'item_61_1760892705.jpeg'),
(62, 24, 'Ampar-Ampar Pisang', 'Ampar-Ampar Pisang adalah salah satu lagu tradisional khas Kalimantan Selatan, namun cukup populer juga di Kalimantan Barat karena sering dipertunjukkan dalam acara budaya anak-anak dan pertunjukan kesenian lokal. Lagu ini biasanya dinyanyikan oleh anak-anak dalam bentuk permainan, sambil melakukan gerakan mengampar atau menabur pisang yang menjadi tema lagu.\r\n\r\nLirik lagu “Ampar-Ampar Pisang” bercerita tentang kegiatan tradisional masyarakat dalam mengolah pisang, yaitu menjemur atau mengampar pisang agar cepat kering. Lagu ini memiliki melodi ceria, ritme cepat, dan mudah diingat, sehingga sering dijadikan sebagai media pembelajaran anak-anak untuk mengenal budaya dan musik tradisional.\r\n\r\nSelain sebagai lagu hiburan, Ampar-Ampar Pisang juga memiliki nilai edukatif dan budaya. Lagu ini mengenalkan anak-anak pada kearifan lokal, kegiatan sehari-hari masyarakat, dan nilai gotong royong, karena dalam proses “ampar-ampar pisang” biasanya dilakukan secara bersama-sama.\r\n\r\nHingga kini, lagu Ampar-Ampar Pisang tetap dilestarikan sebagai bagian dari warisan musik tradisional Indonesia, sering ditampilkan dalam pentas seni, lomba lagu daerah, dan kegiatan pendidikan anak usia dini, sekaligus menjadi simbol kegembiraan dan kreativitas budaya Kalimantan.', 'https://www.youtube.com/embed/gtCS-eJF3kM', 'Sonora.id', '1760894685_ampar pisang.jpeg'),
(63, 24, 'Bubor Paddas', '“Bubur Paddas” adalah salah satu lagu tradisional khas masyarakat Melayu di Kalimantan Barat, khususnya dari daerah Sambas dan Pontianak. Lagu ini biasanya dinyanyikan dalam suasana santai maupun pertunjukan budaya, dengan melodi sederhana, ceria, dan mudah diingat, sehingga sangat populer di kalangan anak-anak maupun dewasa.\r\n\r\nLagu ini bercerita tentang bubur pedas, makanan tradisional Melayu yang kaya rempah dan sayuran, melambangkan kearifan lokal, kebersamaan, dan rasa syukur atas hasil bumi. Melalui lagu ini, masyarakat tidak hanya memperkenalkan kuliner khas mereka, tetapi juga menanamkan nilai gotong royong dan tradisi memasak bersama keluarga.\r\n\r\nSecara budaya, “Bubur Paddas” berfungsi sebagai media edukatif dan hiburan, mengenalkan generasi muda pada tradisi kuliner, musik, dan bahasa lokal. Lagu ini sering dibawakan pada acara adat, perayaan keluarga, maupun pertunjukan seni anak-anak, sehingga menjadi salah satu simbol identitas budaya Melayu Kalimantan Barat.\r\n\r\nHingga kini, lagu “Bubur Paddas” tetap dilestarikan sebagai bagian dari warisan musik tradisional Kalimantan Barat, mengajarkan rasa cinta terhadap budaya, kuliner lokal, dan kebersamaan antarwarga.', 'https://www.youtube.com/embed/I6h8GXn8nqE', 'youtube', '1760894905_bubor paddas.jpeg'),
(64, 21, 'Tari Hudoq', 'Tari Hudoq adalah salah satu tarian tradisional khas suku Dayak yang berasal dari Kalimantan Barat dan Kalimantan Timur, khususnya masyarakat Dayak Bahau, Dayak Modang, dan Dayak Kenyah. Tarian ini merupakan bagian dari upacara adat panen padi, yang dilakukan untuk mengusir roh jahat, penyakit, dan mendatangkan kesuburan serta hasil panen yang melimpah.\r\n\r\nDalam pertunjukannya, para penari mengenakan topeng Hudoq yang terbuat dari kulit kayu, daun, bulu, atau bahan alami lain, dengan motif wajah yang menyeramkan untuk menakut-nakuti roh jahat. Kostum penari biasanya terdiri dari pakaian tradisional Dayak lengkap dengan aksesoris dari daun, rotan, dan anyaman. Tari Hudoq diiringi oleh musik tradisional berupa gong, gendang, dan alat musik perkusi lainnya, menciptakan ritme yang dinamis dan energik.\r\n\r\nTari Hudoq bukan hanya sekadar hiburan, tetapi juga memiliki nilai religius dan simbolis yang mendalam. Tarian ini melambangkan hubungan harmonis antara manusia, alam, dan leluhur, serta menjadi sarana pendidikan budaya bagi generasi muda. Proses latihan dan pertunjukan Tari Hudoq menekankan kerjasama, kekompakan, dan keterampilan gerak di antara para penari.\r\n\r\nHingga kini, Tari Hudoq tetap dilestarikan sebagai bagian penting dari warisan budaya Dayak di Kalimantan Barat. Tarian ini sering ditampilkan pada acara adat, festival budaya, dan kegiatan pariwisata, sekaligus menjadi simbol identitas dan kearifan lokal masyarakat Dayak yang kaya akan nilai-nilai spiritual dan sosial.', 'https://www.youtube.com/embed/nVM10FmnTEc', 'WWF-INDONESIA', '1760895464_Tari Hudoq.jpeg'),
(65, 21, 'Tari Joget Melayu', 'Tari Joget Melayu adalah salah satu tarian tradisional khas masyarakat Melayu di Kalimantan Barat, yang sering ditampilkan dalam acara pernikahan, festival budaya, dan perayaan adat. Tarian ini dikenal karena gerakannya yang luwes, enerjik, dan penuh keanggunan, mencerminkan budaya Melayu yang kaya akan seni dan estetika.\r\n\r\nDalam pertunjukannya, para penari mengenakan pakaian tradisional Melayu, seperti baju kurung untuk perempuan dan baju teluk belanga untuk laki-laki, lengkap dengan aksesoris seperti tengkolok, songket, dan perhiasan tradisional. Gerakan Tari Joget Melayu biasanya bersifat ceria, ritmis, dan melibatkan interaksi antara penari pria dan wanita, sering kali diiringi musik tradisional Melayu berupa gendang, gong, seruling, dan alat musik petik.\r\n\r\nTari Joget Melayu bukan hanya sekadar hiburan, tetapi juga memiliki nilai sosial dan budaya. Tarian ini melambangkan keceriaan, kebersamaan, dan rasa syukur, serta berfungsi sebagai media pembelajaran budaya dan etika sosial bagi generasi muda. Selain itu, Tari Joget Melayu menunjukkan keterampilan menari, ritme, dan keharmonisan gerak yang menjadi ciri khas seni pertunjukan Melayu.\r\n\r\nHingga kini, Tari Joget Melayu tetap dilestarikan sebagai bagian penting dari warisan budaya Melayu di Kalimantan Barat, sering ditampilkan dalam berbagai acara adat, festival budaya, dan pariwisata, serta menjadi simbol keindahan, keramahan, dan identitas masyarakat Melayu Kalimantan Barat.', 'https://www.youtube.com/embed/FEtvvxHSCL8', 'Pinang Paleo', '1760895661_Tari Joget Melayu.jpeg'),
(66, 21, 'Tari Zapin Melayu', 'Tari Zapin Melayu adalah salah satu tarian tradisional Melayu yang populer di Kalimantan Barat, khususnya di daerah pesisir seperti Pontianak dan Sambas. Tarian ini memiliki gerakan yang dinamis, ritmis, dan mengalir, menggabungkan unsur tarian rakyat Melayu dengan pengaruh budaya Arab yang dibawa melalui perdagangan dan penyebaran Islam.\r\n\r\nPara penari Tari Zapin Melayu biasanya mengenakan pakaian tradisional Melayu, seperti baju kurung atau jubah untuk perempuan, dan baju teluk belanga serta samping untuk laki-laki. Tari ini sering dilakukan berpasangan, diiringi musik tradisional Melayu yang terdiri dari gendang, rebana, seruling, dan gong, menciptakan suasana ritmis yang ceria dan enerjik.\r\n\r\nSecara budaya, Tari Zapin Melayu bukan hanya hiburan, tetapi juga media pembelajaran nilai-nilai sosial dan religi, seperti sopan santun, kebersamaan, dan penghormatan terhadap tradisi. Tarian ini sering ditampilkan dalam acara pernikahan, festival budaya, dan upacara adat, serta menjadi simbol identitas Melayu yang religius dan harmonis dengan lingkungan sosialnya.\r\n\r\nHingga kini, Tari Zapin Melayu tetap dilestarikan sebagai bagian penting dari warisan budaya Kalimantan Barat, menunjukkan perpaduan kesenian, agama, dan nilai sosial yang menjadi ciri khas masyarakat Melayu setempat. Tarian ini tidak hanya menghibur, tetapi juga membawa pesan moral dan kearifan lokal yang terus diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/kGpzlNhddHo', 'melayupedia.com', '1760895802_tari zapin.jpeg'),
(67, 21, 'Tari Ngajat', 'Tari Ngajat adalah salah satu tarian tradisional khas suku Dayak di Kalimantan Barat, khususnya suku Iban dan Dayak lainnya. Tarian ini biasanya ditampilkan dalam upacara adat, pesta panen, festival budaya, dan penyambutan tamu penting, sebagai simbol kegembiraan, keberanian, dan rasa syukur atas hasil bumi.\r\n\r\nPara penari Tari Ngajat mengenakan kostum tradisional Dayak lengkap dengan hiasan bulu burung, manik-manik, dan topeng, yang memperkuat estetika dan karakter budaya suku Dayak. Gerakan tari ini dinamis, lincah, dan menonjolkan kekuatan fisik, sering kali meniru gerakan binatang atau aktivitas berburu, serta diiringi musik tradisional seperti gendang, gong, dan alat musik perkusi.\r\n\r\nSecara budaya, Tari Ngajat memiliki makna simbolis yang mendalam. Tarian ini melambangkan keterampilan, keberanian, dan keharmonisan antara manusia dan alam. Selain itu, Tari Ngajat juga menjadi sarana pendidikan budaya bagi generasi muda, mengajarkan nilai kekompakan, kebersamaan, dan penghormatan terhadap leluhur.\r\n\r\nHingga kini, Tari Ngajat tetap dilestarikan sebagai bagian penting dari warisan budaya Dayak di Kalimantan Barat, sering ditampilkan dalam berbagai acara adat, festival, dan kegiatan pariwisata. Tarian ini tidak hanya menghibur, tetapi juga menjadi ikon identitas suku Dayak, sekaligus simbol kearifan lokal dan kreativitas masyarakat Kalimantan Barat.', 'https://www.youtube.com/embed/VASYAV5bTDM', 'VIVA Bali', '1760895912_Tari Ngajat.jpeg'),
(68, 21, 'Tari Mandau / Tandak Dayak', 'Tari Mandau, yang juga dikenal sebagai Tari Tandak Dayak, adalah salah satu tarian tradisional khas suku Dayak di Kalimantan Barat. Tarian ini terinspirasi dari gerakan pertempuran dan keberanian para prajurit Dayak, terutama yang menggunakan mandau, senjata tradisional suku Dayak. Tari ini biasanya ditampilkan dalam upacara adat, festival budaya, penyambutan tamu penting, atau pertunjukan seni Dayak.\r\n\r\nPara penari Tari Mandau mengenakan kostum tradisional Dayak lengkap dengan hiasan bulu, manik-manik, dan aksesori senjata, terutama mandau yang menjadi simbol keberanian dan kehormatan. Gerakan tari ini dinamis, energik, dan menekankan ketangkasan serta kekuatan fisik, sering kali meniru aksi bertarung, berburu, atau aktivitas sehari-hari masyarakat Dayak. Musik pengiring biasanya berupa gendang, gong, dan alat musik perkusi lainnya, menciptakan ritme yang cepat dan bersemangat.\r\n\r\nSecara budaya, Tari Mandau / Tandak Dayak memiliki makna simbolis mendalam, melambangkan keberanian, kehormatan, dan identitas suku Dayak. Tarian ini juga menjadi sarana pendidikan budaya dan nilai moral bagi generasi muda, mengajarkan tentang keberanian, solidaritas, dan penghormatan terhadap leluhur serta alam sekitar.\r\n\r\nHingga kini, Tari Mandau / Tandak Dayak tetap dilestarikan sebagai bagian penting dari warisan budaya Kalimantan Barat, sering ditampilkan dalam berbagai acara adat, festival, dan kegiatan pariwisata, sekaligus menjadi ikon identitas Dayak yang memadukan seni, keberanian, dan tradisi.', 'https://www.youtube.com/embed/yG7kW18BPdY', 'Kompas Regional', '1760896059_Tari Mandau.jpeg'),
(69, 21, 'Tari Kuda Lumping Dayak', 'Tari Kuda Lumping Dayak adalah salah satu tarian tradisional suku Dayak di Kalimantan Barat yang terinspirasi dari keberanian dan kelincahan prajurit Dayak. Meskipun nama “Kuda Lumping” lebih dikenal di Jawa, versi Dayak memiliki ciri khas tersendiri, yaitu gerakan yang meniru kuda dan aktivitas perang atau berburu, serta kostum yang unik sesuai adat Dayak.\r\n\r\nPara penari mengenakan kostum tradisional Dayak lengkap dengan hiasan bulu, manik-manik, dan aksesori senjata, sambil menunggang kuda-kudaan dari anyaman atau kayu. Gerakannya dinamis dan energik, mencerminkan keberanian, kekuatan fisik, serta kelincahan, sementara musik pengiring berupa gendang, gong, dan alat musik perkusi yang menghasilkan ritme cepat dan menggairahkan.\r\n\r\nSecara budaya, Tari Kuda Lumping Dayak memiliki nilai simbolis tinggi. Tarian ini melambangkan keberanian, kehormatan, dan ketangkasan prajurit Dayak, sekaligus menjadi media pendidikan budaya dan moral bagi generasi muda, mengajarkan keberanian, solidaritas, dan penghormatan terhadap leluhur.\r\n\r\nHingga kini, Tari Kuda Lumping Dayak tetap dilestarikan sebagai bagian penting dari warisan budaya Kalimantan Barat, sering ditampilkan dalam acara adat, festival budaya, penyambutan tamu, dan pertunjukan pariwisata. Tarian ini menjadi ikon identitas suku Dayak, memadukan seni, keberanian, dan tradisi lokal dalam satu pertunjukan yang memukau.', 'https://www.youtube.com/embed/LZuvOblNdqg', 'archipelagoid.com', '1760896236_Tari Kuda Lumping Dayak.jpeg'),
(70, 21, 'Tari Dayang Kumang', 'Tari Dayang Kumang adalah salah satu tarian tradisional khas suku Dayak di Kalimantan Barat, khususnya suku Iban dan Dayak Kenyah. Tarian ini dikenal sebagai tarian penyambutan tamu, yang memperlihatkan keanggunan, keramahan, dan kecantikan para perempuan Dayak.\r\n\r\nPara penari Tari Dayang Kumang biasanya adalah perempuan muda yang mengenakan kostum tradisional Dayak lengkap dengan hiasan manik-manik, bulu, dan songket, serta memegang tali atau kipas untuk memperindah gerakan. Gerakan tari ini lembut, anggun, dan ritmis, menampilkan keseimbangan antara keindahan tubuh dan ekspresi wajah, mencerminkan nilai-nilai sopan santun dan keramahan khas budaya Melayu-Dayak.\r\n\r\nSecara budaya, Tari Dayang Kumang memiliki makna simbolis penting. Tarian ini melambangkan kehormatan, kesopanan, dan penghargaan terhadap tamu, sekaligus menjadi media pendidikan budaya dan pengenalan adat istiadat bagi generasi muda. Tarian ini sering ditampilkan dalam acara adat, festival budaya, dan penyambutan tamu penting, menunjukkan kebanggaan masyarakat Dayak terhadap warisan budayanya.\r\n\r\nHingga kini, Tari Dayang Kumang tetap dilestarikan sebagai ikon budaya Kalimantan Barat, menjadi simbol keanggunan, keramahan, dan identitas suku Dayak, serta memperkuat nilai-nilai sosial dan kearifan lokal yang diwariskan dari generasi ke generasi.', 'https://www.youtube.com/embed/_9qelljGsgY', 'youtube', '1760896436_Tari Dayang Kumang.jpeg'),
(71, 19, 'Pakaian Adat Dayak Iban', 'Pakaian Adat Dayak Iban adalah busana tradisional khas suku Dayak Iban yang mendiami wilayah Kalimantan Barat, khususnya daerah Kapuas Hulu dan sekitarnya. Pakaian ini mencerminkan identitas budaya, nilai estetika, dan kearifan lokal suku Dayak Iban, serta sering digunakan dalam upacara adat, festival budaya, perayaan panen, dan penyambutan tamu penting.\r\n\r\nUntuk perempuan, pakaian adat Dayak Iban biasanya terdiri dari atasan dan rok panjang yang terbuat dari kain tenun tradisional dengan motif khas Dayak, dihiasi manik-manik, bulu, dan sulaman yang memperindah tampilan. Aksesori tambahan seperti kalung, gelang, dan hiasan kepala juga sering digunakan untuk menegaskan status sosial dan keindahan.\r\n\r\nLaki-laki mengenakan rompi atau baju pendek dari kain tenun, dipadukan dengan celana panjang sederhana, ikat kepala, dan kadang dilengkapi dengan senjata tradisional seperti mandau atau parang, yang melambangkan keberanian dan kehormatan.\r\n\r\nSecara budaya, pakaian adat Dayak Iban tidak hanya berfungsi sebagai busana, tetapi juga mewakili identitas komunitas, status sosial, dan nilai-nilai tradisional. Motif dan hiasan pada pakaian mengandung simbol-simbol spiritual, perlindungan, dan penghormatan terhadap leluhur.\r\n\r\nHingga kini, Pakaian Adat Dayak Iban tetap dilestarikan sebagai bagian penting dari warisan budaya Kalimantan Barat, sering ditampilkan dalam pertunjukan seni, festival budaya, upacara adat, dan kegiatan pariwisata. Busana ini menjadi ikon identitas suku Dayak Iban, memadukan seni, tradisi, dan kearifan lokal dalam satu tampilan yang indah dan penuh makna.', 'https://www.youtube.com/embed/xtZXYMh0f-w', 'Kalimantan Review', '1760915249_Pakaian Adat Dayak Iban.jpeg'),
(72, 19, 'Pakaian Adat Bidayuh', 'Pakaian Adat Bidayuh adalah busana tradisional khas suku Bidayuh yang mendiami wilayah perbatasan Kalimantan Barat dan Sarawak, Malaysia. Pakaian ini mencerminkan identitas budaya, estetika, dan kearifan lokal suku Bidayuh, serta sering digunakan dalam acara adat, ritual, perayaan panen, dan festival budaya.\r\n\r\nPakaian adat Bidayuh memiliki ciri khas berupa bahan tenun tradisional dengan warna alami, dihiasi motif geometris dan simbol-simbol khas suku Bidayuh. Untuk perempuan, busana biasanya terdiri dari kain panjang yang membungkus tubuh, dipadukan dengan atasan pendek atau rompi, serta aksesori seperti manik-manik, kalung, dan gelang. Laki-laki mengenakan celana panjang sederhana, rompi, dan ikat kepala, sering kali juga dilengkapi dengan senjata tradisional seperti parang atau mandau sebagai simbol keberanian.\r\n\r\nSecara budaya, pakaian adat Bidayuh tidak hanya berfungsi sebagai busana sehari-hari atau seremonial, tetapi juga mewakili status sosial, identitas komunitas, dan nilai-nilai tradisional. Setiap motif dan hiasan memiliki makna tersendiri, mulai dari simbol kesuburan, keberanian, hingga perlindungan dari roh jahat.\r\n\r\nHingga kini, Pakaian Adat Bidayuh tetap dilestarikan sebagai bagian penting dari warisan budaya Kalimantan Barat, sering ditampilkan dalam pertunjukan seni, festival budaya, dan kegiatan pariwisata. Busana ini menjadi ikon identitas suku Bidayuh, memadukan seni, tradisi, dan kearifan lokal dalam satu tampilan yang indah dan bermakna.', 'https://www.youtube.com/embed/ajo7hPI5dDk', 'kalbar.jadesta.com', '1760915313_Pakaian Adat Bidayuh.jpeg'),
(73, 19, 'Baju Kurung / Baju Melayu', 'Baju Kurung atau Baju Melayu adalah pakaian tradisional khas masyarakat Melayu yang banyak digunakan di Kalimantan Barat, terutama di daerah pesisir seperti Pontianak dan Sambas. Pakaian ini menjadi simbol identitas budaya, kesopanan, dan keanggunan masyarakat Melayu, serta sering dipakai dalam acara adat, keagamaan, pernikahan, dan festival budaya.\r\n\r\nBaju Kurung umumnya terdiri dari atasan longgar dan rok panjang untuk perempuan, yang memudahkan gerakan dan memberikan kesan anggun. Bahan yang digunakan biasanya songket, katun, atau kain tenun tradisional, sering dihiasi dengan motif sulaman, bordiran, atau manik-manik yang memperindah tampilan.\r\n\r\nSementara itu, Baju Melayu untuk laki-laki biasanya berupa atasan longgar dengan lengan panjang dan kerah bulat atau tegak, dipadukan dengan sarung atau kain samping, dan kadang dilengkapi dengan tengkolok atau peci. Busana ini menonjolkan kesederhanaan, kerapian, dan kesopanan, sesuai dengan nilai-nilai budaya Melayu.\r\n\r\nSelain fungsi praktis, Baju Kurung dan Baju Melayu memiliki makna sosial dan simbolik. Pakaian ini menunjukkan identitas budaya, rasa hormat terhadap tradisi, dan kebanggaan terhadap warisan leluhur. Hingga kini, keduanya tetap dilestarikan sebagai ikon budaya Kalimantan Barat, digunakan dalam pertunjukan seni, festival budaya, acara adat, maupun kegiatan pariwisata, sekaligus menjadi lambang keanggunan dan keharmonisan masyarakat Melayu.', 'https://www.youtube.com/embed/6CBdqLJNhqI', 'Pinterest', '1760915412_Baju Kurung.jpeg'),
(74, 19, 'Baju Teluk Belanga / Baju Kurung Sambas', 'Baju Teluk Belanga dan Baju Kurung Sambas adalah pakaian tradisional khas Melayu Kalimantan Barat, yang sering digunakan oleh masyarakat Melayu dalam berbagai acara adat, keagamaan, dan perayaan resmi. Kedua jenis baju ini memiliki makna budaya dan simbolik, mencerminkan identitas dan estetika masyarakat Melayu Sambas.\r\n\r\nBaju Teluk Belanga biasanya dikenakan oleh laki-laki. Pakaian ini memiliki potongan sederhana dengan kerah bulat (belanga) tanpa lipatan, lengan panjang, dan dipadukan dengan sarung atau kain samping. Baju ini sering dipakai pada acara resmi, pernikahan, atau festival budaya, menunjukkan kesopanan dan keanggunan pemakainya.\r\n\r\nBaju Kurung Sambas dikenakan oleh perempuan. Pakaian ini terdiri dari atasan longgar dan rok panjang, sering dihiasi dengan motif sulaman, manik-manik, atau bordiran yang mencerminkan keindahan dan kerajinan tangan lokal. Baju Kurung juga dipakai dalam acara adat, pesta pernikahan, dan pertunjukan budaya, memperlihatkan keanggunan dan kelembutan perempuan Melayu.\r\n\r\nKedua pakaian ini tidak hanya berfungsi sebagai busana, tetapi juga membawa nilai sosial dan budaya. Pemakaian Baju Teluk Belanga dan Baju Kurung Sambas menunjukkan identitas Melayu, rasa hormat terhadap tradisi, dan kebanggaan akan warisan budaya. Hingga kini, kedua pakaian tradisional ini tetap dilestarikan dan dipromosikan sebagai ikon budaya Kalimantan Barat, sering digunakan dalam festival, pertunjukan seni, dan kegiatan pariwisata.', 'https://www.youtube.com/embed/8recSkpWguo', 'bobo.grid.id', '1760915494_Baju Teluk Belanga.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `kategori`
--

CREATE TABLE `kategori` (
  `id` int(10) NOT NULL,
  `nama_kategori` varchar(100) NOT NULL,
  `foto` varchar(255) DEFAULT 'default.jpg'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `kategori`
--

INSERT INTO `kategori` (`id`, `nama_kategori`, `foto`) VALUES
(18, 'Kuliner', 'kategori_68e27c55d2c49.avif'),
(19, 'Pakaian Adat', 'kategori_68e27cc56fd55.jpeg'),
(20, 'Senjata Tradisional', 'kategori_68e27d6988ff2.jpeg'),
(21, 'Tarian Adat', 'kategori_68e27db0dacf8.webp'),
(22, 'Alat Musik Tradisional', 'kategori_68e27df50c3cf.jpeg'),
(23, 'Upacara Adat', 'kategori_68e27e23c4258.jpeg'),
(24, 'Lagu Tradisional', 'kategori_68e27e5f4b4ab.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `isi_kategori`
--
ALTER TABLE `isi_kategori`
  ADD PRIMARY KEY (`id`),
  ADD KEY `kategori_id_idx` (`kategori_id`);

--
-- Indexes for table `kategori`
--
ALTER TABLE `kategori`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `nama_kategori` (`nama_kategori`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=242454;

--
-- AUTO_INCREMENT for table `isi_kategori`
--
ALTER TABLE `isi_kategori`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=76;

--
-- AUTO_INCREMENT for table `kategori`
--
ALTER TABLE `kategori`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `isi_kategori`
--
ALTER TABLE `isi_kategori`
  ADD CONSTRAINT `fk_kategori` FOREIGN KEY (`kategori_id`) REFERENCES `kategori` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
